export const authSelectors = {
  emailInput: "email-input-field",
  phoneInput: "phone-number-input-field",
  passwordInput: "password-input-field",
  confirmPasswordInput: "confirm-password-input-field",
  showPasswordButton: "show-password-button",
  showConfirmPasswordButton: "show-confirm-password-button",
  signUpButton: "sign-up-button",
  signInButton: "sign-in-button",
  goToSignUpPageButton: "go-to-sign-up-page-button",
  goToSignInPageButton: "go-to-sign-in-page-button",
  forgotPasswordButton: "forgot-password-button",
  resetPasswordButton: "reset-password-button",
  resendEmailButton: "resend-email-button",
  saveNewPasswordButton: "save-new-password-button",
  cancelNewPasswordButton: "cancel-new-password-button",
  signUpWithGoogleButton: "sign-up-with-google-button",
  signUpWithFacebookButton: "sign-up-with-facebook-button",
  signUpWithAppleButton: "sign-up-with-apple-button",
  validationError: "p.Mui-error",
} as const;
