export enum ErrorKey {
  Default = "Default",
  InvalidParameterException = "InvalidParameterException",
  InvalidPasswordException = "InvalidPasswordException",
  NotAuthorizedException = "NotAuthorizedException",
  TooManyRequestsException = "TooManyRequestsException",
  UnsupportedUserStateException = "UnsupportedUserStateException",
  UserNotPermission = "UserNotPermission",
  UserNotAlignToGroup = "UserNotAlignToGroup",
  UsernameExistsException = "UsernameExistsException",
  UserNotFoundException = "UserNotFoundException",
  TooManyCheck = "TooManyCheck",
  WrongPhoneNumber = "WrongPhoneNumber",
  WrongEmailAddress = "WrongEmailAddress",
}
